// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzxSlZvQ-q7oRnIoaxbV52P8J3E5eTeno',
    appId: '1:434016335610:android:c76b95cd542aeb6c5cbb43',
    messagingSenderId: '434016335610',
    projectId: 'tester-9ca76',
    databaseURL: 'https://tester-9ca76-default-rtdb.firebaseio.com',
    storageBucket: 'tester-9ca76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFIGczS-FHHmcKkB5OyondsdLBSjTvV8',
    appId: '1:434016335610:ios:f04e95f15cdcc06d5cbb43',
    messagingSenderId: '434016335610',
    projectId: 'tester-9ca76',
    databaseURL: 'https://tester-9ca76-default-rtdb.firebaseio.com',
    storageBucket: 'tester-9ca76.appspot.com',
    iosClientId: '434016335610-832d9emu02us4ic6dv4h41c5lock89j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2',
  );
}
